stages:
    - build
    - deploy
  
composer:
    stage: build
    cache:
        key: composer
        paths:
        - ./src/vendor/
    script:
        - cd ./src
        - composer install
    artifacts:
        expire_in: 1 month
        paths:
        - ./src/vendor/
    tags:
      - dl-dev
    only:
      refs:
        - main

.base_deploy: &base_deploy
  script:
    - sudo rm -Rf $PROJECT_PATH/builds/$CI_PIPELINE_ID
    - sudo cp -a ./src/ $PROJECT_PATH/builds/$CI_PIPELINE_ID
    - sudo ln -sn $PROJECT_PATH/shared/.env $PROJECT_PATH/builds/$CI_PIPELINE_ID/.env
    - cd  $PROJECT_PATH/builds/$CI_PIPELINE_ID/
    - php artisan migrate --force
    - sudo rm -rf $PROJECT_PATH/builds/$CI_PIPELINE_ID/storage
    - sudo ln -sn $PROJECT_PATH/shared/storage $PROJECT_PATH/builds/$CI_PIPELINE_ID/storage
    - sudo ln -sn $PROJECT_PATH/shared/storage/app/public $PROJECT_PATH/builds/$CI_PIPELINE_ID/public/storage
    - sudo ln -sfn $PROJECT_PATH/builds/$CI_PIPELINE_ID/ $PROJECT_PATH/website
    - sudo chown -R www:www $PROJECT_PATH/builds
    - sudo chmod -R 777 $PROJECT_PATH/builds
    - cd $PROJECT_PATH/builds
    - shopt -s extglob
    - rm -rf !("$CI_PIPELINE_ID")

deploy_stage:
    stage: deploy
    <<: *base_deploy
    before_script:
      # - "sudo supervisorctl stop ss_stage:"
    after_script:
      # - "sudo supervisorctl start ss_stage:"
    environment:
        name: dev
        url: https://hack-api.projects.dl-net.ru
    only:
      refs:
        - main
    tags:
      - dl-dev
